# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FerqUn2J7E6ZwEbiYhMQN90cRpPIcIH8
"""

print('hola mundo')